Add a test to demonstrate that a NoClassDefFoundError is throwed when a a composite is imported from a jar which not contains all the required classes.